language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
before_install:
  - pip install flake8
install:
  - python setup.py install
script:
  - flake8 . --exclude __init__.py
  - py.test tests/
